## Excercise 3.1.a
### @packkkk
---

In [5]:
import numpy as np
#3.1.a.1
arr1 = np.arange(10)
print(arr1)
print(arr1.size)
print(arr1.dtype)

[0 1 2 3 4 5 6 7 8 9]
10
int64


In [13]:
#3.1.a.2
arr1_odd = arr1[np.where(arr1 % 2 == 0)]
print (arr1_odd)
arr1_even = arr1[np.where(arr1 % 2 != 0)]
print (arr1_even)

[  0 100   2 100   4 100   6 100   8 100]
[]


In [12]:
#3.1.a.3
arr1[arr1_even] = 100
print (arr1)

[  0 100   2 100   4 100   6 100   8 100]
