# Excercise 2.1
## @packkkk
---
### My top 5 websites:
* Medium [Home Page](https://medium.com/)
* Reddit [Home Page](https://reddit.com/)
* BleepingComputers [Home Page](https://www.bleepingcomputer.com/)
* Udemy [Home Page](https://www.udemy.com/)
* Github [Home Page](https://github.com/)

1. Medium [Home Page](https://medium.com/)
2. Reddit [Home Page](https://reddit.com/)
3. BleepingComputers [Home Page](https://www.bleepingcomputer.com/)
4. Udemy [Home Page](https://www.udemy.com/)
5. Github [Home Page](https://github.com/)

* List
* List
* List

1. one
2. two
3. three

> Blockquote

- One
- Two 
- Three

# Excercise 2.2
## @packkkk
---
### Tiểu sử Blaise Pascal:

***Blaise Pascal*** (tiếng Pháp: ***[blɛz paskal]***; **19 tháng 6 năm 1623 – 19 tháng 8 năm 1662**) (tên khác: Lee Central Paint) là nhà toán học, vật lý, nhà phát minh, tác gia, và triết gia Cơ Đốc người Pháp. Là cậu bé thần đồng, Pascal tiếp nhận nền giáo dục từ cha, một quan chức thuế vụ tại Rouen, trong khi mẹ ông mất sớm. Nghiên cứu đầu tay của Pascal là trong lĩnh vực tự nhiên và khoa học ứng dụng, là những đóng góp quan trọng cho nghiên cứu về chất lưu, và làm sáng tỏ những khái niệm về áp suất và chân không bằng cách khái quát hóa công trình của Evangelista Torricelli. Pascal cũng viết để bảo vệ phương pháp khoa học.

Năm 1642, khi còn là một thiếu niên, Pascal bắt tay vào một số nghiên cứu tiên phong về máy tính. Sau ba năm nỗ lực với năm mươi bản mẫu, cậu đã phát minh máy tính cơ học, chế tạo 20 máy tính loại này (gọi là máy tính Pascal, về sau gọi là Pascaline) trong vòng mười năm. Pascal là một nhà toán học tài danh, giúp kiến tạo hai lĩnh vực nghiên cứu quan trọng: viết một chuyên luận xuất sắc về hình học xạ ảnh khi mới 16 tuổi, rồi trao đổi với Pierre de Fermat về lý thuyết xác suất, có ảnh hưởng sâu đậm trên tiến trình phát triển kinh tế học và khoa học xã hội đương đại. Tiếp bước Galileo và Torricelli, năm 1646, ông phản bác những người theo Aristotle chủ trương thiên nhiên không chấp nhận khoảng không. Kết quả nghiên cứu của Pascal đã gây ra nhiều tranh luận trước khi được chấp nhận.

Năm 1646, Pascal và em gái Jacqueline gia nhập một phong trào tôn giáo phát triển bên trong Công giáo mà những người gièm pha gọi là thuyết Jansen. Cha ông mất năm 1651. Tiếp sau một trải nghiệm tâm linh xảy ra cuối năm 1654, ông trải qua "sự qui đạo thứ nhì", từ bỏ nghiên cứu khoa học, và hiến mình cho triết học và thần học. Hai tác phẩm nổi tiếng nhất của Pascal đánh dấu giai đoạn này: Lettres provinciales (Những lá thư tỉnh lẻ) và Pensées (Suy tưởng), tác phẩm đầu được ấn hành trong bối cảnh tranh chấp giữa nhóm Jansen với Dòng Tên. Cũng trong năm này, ông viết một luận văn quan trọng về tam giác số học.

Pascal có thể chất yếu đuối, nhất là từ sau 18 tuổi đến khi qua đời, chỉ hai tháng trước khi tròn 39 tuổi.

***Nguồn [Wikipedia](https://vi.wikipedia.org/wiki/Blaise_Pascal)***

# Excercise 2.3
## @packkkk
---
### Top 5 Favourite Courses:

| Number | Name | Length |
| :---: | :---: | :---: |
| 1 | Nhap mon lap trinh | 108 hours |
| 2 | Cau truc du lieu va giai thuat | 108 hours |
| 3 | Nhap mon mang can ban | 108 hours |
| 4 | An toan kien truc he thong | 108 hours |
| 5 | An toan mang can ban/nang cao | 108 hours |

# Excercise 2.4
## @packkkk
---
### Formulas:

1. Định lý hàm số cosin:

    $ a^2 = b^2 + c^2 - 2bc\cos{A} $
    
    $ b^2 = a^2 + c^2 - 2ac\cos{B} $
    
    $ c^2 = a^2 + b^2 - 2ab\cos{C} $

2. Định lý hàm số sin:

    $ \frac{a}{\sin{A}} = \frac{b}{\sin{B}} = \frac{c}{\sin{C}} = 2R $

3. Công thức độ dài trung tuyến:

    $ m_a = \sqrt{\frac{b^2 + c^2}{2} - \frac{a^2}{4}} $ ; $ m_b = \sqrt{\frac{a^2 + c^2}{2} - \frac{b^2}{4}} $ ; $ m_c = \sqrt{\frac{a^2 + b^2}{2} - \frac{c^2}{4}} $

4. Công thức biến đổi căn thức:
    
    $ \sqrt{A^2} = |a| $

5. Gradient Tree Boosting Algorithm:

    * Initialize model with a constant value
    $f_0(x) = arg min_x\sum_{i=1}^{N} L(y_i,y)$

In [5]:
import numpy as np
array_1 = np.array([1,2,3])
print(array_1)
print(type(array_1))

[1 2 3]
<class 'numpy.ndarray'>


In [6]:
np.ones(4)

array([1., 1., 1., 1.])

In [9]:
np.zeros((5,), dtype=np.int)

array([0, 0, 0, 0, 0])

In [10]:
np.asarray((1,2,3))

array([1, 2, 3])

In [11]:
mang_2=np.arange(10, 20.2)
print(mang_2)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]


In [12]:
mang_3 = np.linspace(10, 20, 5)
print(mang_3)
mang_4 = np.linspace(10, 20, 5, endpoint = False)
print(mang_4)

[10.  12.5 15.  17.5 20. ]
[10. 12. 14. 16. 18.]


In [13]:
print(mang_2.shape[0])

11


In [14]:
mang_2[1] = 250
print(mang_2)

[ 10. 250.  12.  13.  14.  15.  16.  17.  18.  19.  20.]


In [20]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 100)
print (arr)
print (ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[29 45 24 41 46  3 13 27  7 34  1  1 45 22 35 27  7 21 38  3 31 40 33 25
 16 26 26  2 38 38 38  2 26 11 17 43 26 43 38 45 13 20  3 29 13 47 22 41
 20  8  7 26 37 37 25 22 44 49 28 11 15  5 22 15 10  2 38 28  4 44 12 39
 41 43 25  8 23 19 10  0 38  8 39  9  8 24 10 49  0 19 46 26 25  6 22 45
 38 17 31 17]


In [21]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
ranarr.max()

49

In [23]:
ranarr.min()

0

In [24]:
ranarr.argmax()

57

In [25]:
ranarr.argmin()

79

In [27]:
arr.shape

(25,)

In [28]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [29]:
arr.dtype

dtype('int64')

In [30]:
mang_5 = np.arange(10)
print(mang_5)
s = slice(3, 8, 2)
print(mang_5[s])
print(mang_5[s][1])

[0 1 2 3 4 5 6 7 8 9]
[3 5 7]
5


In [35]:
mang_5 = np.append(mang_5, "hi")
mang_5

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'gi', 'gi', 'hi'],
      dtype='<U21')